### ISSUE TITLE
问一下,你2.4.7.的.so文件是是不是前几天miao1007改了源码带了心跳编译后的.so

### ISSUE THREAD

**Issue by Knaithe** [xratzh/hiwifi-netkeeper#1]

**Comment by Sung-yy** [comment]
修改Mian.c后的编译的 .so文件?

**Comment by xratzh** [comment]
@Sung-yy 我刚才编译后上传更新了，没更新的都是03/31编译的，之前的用着一切正常。不过2.4.7的我没测试是否能用，你自己测试一下，欢迎反馈

**Comment by Sung-yy** [comment]
我用的湖北的,2.4.7的,为了方便,我就改名hubei_sxplugin.so为wuhan_sxplugin.so,拨不上去号.

**Comment by Sung-yy** [comment]
帮我看一下,我编译的时候出错了
<img width="391" alt="kk" src="https://cloud.githubusercontent.com/assets/22469662/24642930/384745b0-193d-11e7-99ec-d3d52e7a7663.PNG">
有没可以2.4.7用的编译工具.

**Comment by Sung-yy** [comment]
我直接用的miao1007的那套方法,把把你编译.so文件把以前的.so替换掉,使用了cofnetwork.sh,同步时间,然后拨不上去号了,

**Comment by xratzh** [comment]
我不知道武汉的是怎么回事，你按照我readme.md内容的三个步骤手动来操作。
１、传输.so
２、设置/etc/config/network
３、同步时间或者路由器通过网页同步浏览器时间
不行的话我也没办法

**Comment by Sung-yy** [comment]
谢谢!

**Comment by Sung-yy** [comment]
问一下,我用你的编译的.os文件拨不上去号,上日志
![Uploading 捕获.PNG…]()

**Comment by Sung-yy** [comment]
<img width="660" alt="default" src="https://cloud.githubusercontent.com/assets/22469662/24990817/221e2c14-2049-11e7-8d7b-697eaf9bdd01.PNG">

**Comment by xratzh** [comment]
@Sung-yy 现在还没有结果么？我估计已经拨号成功了吧，应该有ip吧。都是正常加载了，等一会儿会有结果吧

**Comment by Sung-yy** [comment]
我再去试一试

**Comment by Sung-yy** [comment]
没有啊，一直重复循环我发的图片上的工作，那个hook status=1是表示账号算对了了还是算错了，到uid=0然后又开始了新的算号工作，反正重复图片上的内容，是不是算错了账号？

**Comment by xratzh** [comment]
@Sung-yy 你确认自己选择了正确的版本，如果还是这样我自己就没办法了，我这边也还未能测试2.4.7的版本的可用性，所以你要是设置正确后不能用，说明可能编译出错了，也可能算法出问题了。

**Comment by Sung-yy** [comment]
我用centos编译的话应该没问题吧?

**Comment by xratzh** [comment]
@Sung-yy ubuntu还是centos都不影响编译的结果。

**Comment by Sung-yy** [comment]
再问一下,Openwrt-NetKeeper/src/DaoNet/DaoNet/下面的main.c有编译进去吗?

**Comment by Sung-yy** [comment]
![image](https://cloud.githubusercontent.com/assets/22469662/24993874/d865a4b4-205a-11e7-9eab-49fbae255d9d.png)

**Comment by Sung-yy** [comment]
这是什么问题啊,大佬!

**Comment by xratzh** [comment]
你下载toolchain，再解压

**Comment by Sung-yy** [comment]
<img width="445" alt="default" src="https://cloud.githubusercontent.com/assets/22469662/25037029/78a33404-2129-11e7-995f-723ba6670d8b.PNG">

**Comment by Sung-yy** [comment]
是不是我们配置环境变量啊,但是那个error是怎么回事?
