### ISSUE TITLE
arm的这个方法似乎并不能正常工作

### ISSUE THREAD

**Issue by lee86** [xratzh/hiwifi-netkeeper#2]
arm的这个方法似乎并不能正常工作

**Comment by xratzh** [comment]
@lee86 我自己也是梅林，我这边能用，我把so文件上传到路由器/jffs/ppp/chongqing_sxplugin.so，然后：
1、先在wan联机类型选择动态ip，然后在系统管理-->系统设置里面通过校内ntp同步时间（在系统记录里面查看自己的时间是否正确，梅林断电会丢失时间）
2、在wan联机类型选择PPPoE，用户名和密码照常填写，在高级pppd选项填写：plugin /jffs/ppp/chongqing_sxplugin.so，然后应用设置就好了。
或者你可以命令killall pppd && /usr/sbin/pppd file /tmp/ppp/options.wan0

**Comment by lee86** [comment]
nice,看来开始是ntp时间同步的问题，现在还差个心跳了

**Comment by lee86** [comment]
昨天还会掉线，今天很稳定，感谢🙏

**Comment by xratzh** [comment]
@lee86 我这里是周一到周五7点才有网络，周末不断网。所以我在crontab里设置了每天7点执行killall pppd && /usr/sbin/pppd file /tmp/ppp/options.wan0，定时断网重拨。就避免了重启和重新设置时间的麻烦。

**Comment by lee86** [comment]
嗯，我们也差不多是这样的，现在每次登陆都要去微信先清除一次pin，电信有毒
